<?php

/*
 +--------------------------------------------------------------------+
 | CiviCRM version 3.3                                                |
 +--------------------------------------------------------------------+
 | Copyright CiviCRM LLC (c) 2004-2010                                |
 +--------------------------------------------------------------------+
 | This file is a part of CiviCRM.                                    |
 |                                                                    |
 | CiviCRM is free software; you can copy, modify, and distribute it  |
 | under the terms of the GNU Affero General Public License           |
 | Version 3, 19 November 2007.                                       |
 |                                                                    |
 | CiviCRM is distributed in the hope that it will be useful, but     |
 | WITHOUT ANY WARRANTY; without even the implied warranty of         |
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
 | See the GNU Affero General Public License for more details.        |
 |                                                                    |
 | You should have received a copy of the GNU Affero General Public   |
 | License and the CiviCRM Licensing Exception along                  |
 | with this program; if not, contact CiviCRM LLC                     |
 | at info[AT]civicrm[DOT]org. If you have questions about the        |
 | GNU Affero General Public License or the licensing of CiviCRM,     |
 | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
 +--------------------------------------------------------------------+
*/

/**
 *
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2010
 * $Id$
 *
 */

define( 'PARENT_EVENT_ID'  , 1 );
define( 'PARENT_PROFILE_ID', 9 );

function _civicrm_event_parent_get_children_info( $contactID, &$form ) {
    $sql = "
SELECT     c.id as child_id, c.first_name, c.last_name, e.email,
           p.id as parent_id
FROM       civicrm_contact c
INNER JOIN civicrm_relationship r ON c.id = r.contact_id_b
INNER JOIN civicrm_contact      p ON p.id = r.contact_id_a
LEFT  JOIN civicrm_email        e ON c.id = e.contact_id
WHERE      p.id = %1
AND        r.relationship_type_id = 1
AND        r.is_active = 1
";
    $params = array( 1 => array( $contactID, 'Integer' ) );
    $dao = CRM_Core_DAO::executeQuery( $sql, $params );

    $children = array( );
    while ( $dao->fetch( ) ) {
        $children[] = array( 'child_id'   => $dao->child_id  ,
                             'parent_id'  => $dao->parent_id ,
                             'first_name' => $dao->first_name,
                             'last_name'  => $dao->last_name ,
                             'email'      => $dao->email );
    }
    
    if ( ! empty( $children ) ) {
        $form->set( 'children', $children );
    }

    return $children;
}

function civicrm_event_parent_civicrm_buildForm( $formName, &$form ) {
    if ( $formName == 'CRM_Event_Form_Registration_Register' &&
         $form->getVar( '_eventId' ) == PARENT_EVENT_ID ) {
        $mainID = CRM_Utils_Request::retrieve( 'mainID', 'Integer', $form,
                                               false, null, $_REQUEST );
        if ( $mainID ) {
            $rTypeID  = CRM_Utils_Request::retrieve( 'rTypeID', 'Integer', $form,
                                                    false, null, $_REQUEST );
            $rTypeDir = CRM_Utils_Request::retrieve( 'rTypeDir', 'String', $form,
                                                     false, 'a_b', $_REQUEST );
            if ( $rTypeID ) {
                $form->set( 'mainID'  , $mainID   );
                $form->set( 'rTypeID' , $rTypeID  );
                $form->set( 'rTypeDir', $rTypeDir );
            }

            // now set the various defaults
            // basically name and email and number of children
            $children = _civicrm_event_parent_get_children_info( $mainID, $form );

            if ( ! empty( $children ) ) {
                $defaults = array( );
                $defaults['additional_participants'] = count( $children ) - 1;
                $defaults['first_name'] = $children[0]['first_name'];
                $defaults['last_name' ] = $children[0]['last_name' ];
                $defaults['email-5'   ] = $children[0]['email'     ];
                $form->setDefaults( $defaults );
            }
        }
    }
}

function civicrm_event_parent_civicrm_postProcess( $class, &$form ) {
    if ( is_a( $form, 'CRM_Event_Form_Registration_Confirm' ) ) {
        return civicrm_event_parent_civicrm_postProcess_regConfirm( $class, $form );
    }

    if ( is_a( $form, 'CRM_Profile_Form_Edit' ) ) {
        return civicrm_event_parent_civicrm_postProcess_profileEdit( $class, $form );
    }
}

function civicrm_event_parent_civicrm_postProcess_regConfirm( $class, &$form ) {
    if ( $form->getVar( '_eventId' ) == PARENT_EVENT_ID &&
         $form->get( 'mainID' ) ) {
        $mainID   = $form->get( 'mainID'   );
        $rTypeID  = $form->get( 'rTypeID'  );
        $rTypeDir = $form->get( 'rTypeDir' );

        // get the participantIDS
        $participantIDs = $form->getVar( '_participantIDS' );
        
        $pIDString = implode( ',', $participantIDs );

        // get all the contactIDs for these participants
        $sql = "
SELECT contact_id
FROM   civicrm_participant
WHERE  id IN ( $pIDString )
";

        if ( $rTypeDir == 'a_b' ) {
            $mainLabel  = 'a';
            $otherLabel = 'b';
        } else {
            $mainLabel  = 'b';
            $otherLabel = 'a';
        }

        $dao = CRM_Core_DAO::executeQuery( $sql );
        require_once 'api/v2/Relationship.php';
        while ( $dao->fetch( ) ) {
            // create the relationship
            $params = array( "contact_id_{$mainLabel}"  => $mainID,
                             "contact_id_{$otherLabel}" => $dao->contact_id,
                             'relationship_type_id'     => $rTypeID,
                             'is_active'                => 1,
                             );
            civicrm_relationship_create( $params );
        }
    }
}

function civicrm_event_parent_civicrm_postProcess_profileEdit( $class, &$form ) {
    if ( $form->getVar( '_gid' ) == PARENT_PROFILE_ID ) {
        // get the contactID of the newly created contact (or existing one)
        // and redirect to event registration page
        $mainID = $form->getVar( '_id' );

        if ( $mainID ) {
            $url = CRM_Utils_System::url( 'civicrm/event/register',
                                          "reset=1&id=1&cid=0&mainID={$mainID}&rTypeID=1&rTypeDir=b_a" );
            CRM_Utils_System::redirect( $url );
        }
    }
}
